name: Tests

on: push

jobs:
  test:
    name: Run Chip Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Test Chapter 01/Not
        run: ./tools/HardwareSimulator.sh ./01/Not.tst
      - name: Test Chapter 01/And
        run: ./tools/HardwareSimulator.sh ./01/And.tst
      - name: Test Chapter 01/Or
        run: ./tools/HardwareSimulator.sh ./01/Or.tst
      - name: Test Chapter 01/Xor
        run: ./tools/HardwareSimulator.sh ./01/Xor.tst
      - name: Test Chapter 01/Mux
        run: ./tools/HardwareSimulator.sh ./01/Mux.tst
      - name: Test Chapter 01/DMux
        run: ./tools/HardwareSimulator.sh ./01/DMux.tst
      - name: Test Chapter 01/Not16
        run: ./tools/HardwareSimulator.sh ./01/Not16.tst
      - name: Test Chapter 01/And16
        run: ./tools/HardwareSimulator.sh ./01/And16.tst
      - name: Test Chapter 01/Or16
        run: ./tools/HardwareSimulator.sh ./01/Or16.tst
      - name: Test Chapter 01/Mux16
        run: ./tools/HardwareSimulator.sh ./01/Mux16.tst
      - name: Test Chapter 01/Or8Way
        run: ./tools/HardwareSimulator.sh ./01/Or8Way.tst
      - name: Test Chapter 01/Mux4Way16
        run: ./tools/HardwareSimulator.sh ./01/Mux4Way16.tst
      - name: Test Chapter 01/Mux8Way16
        run: ./tools/HardwareSimulator.sh ./01/Mux8Way16.tst
      - name: Test Chapter 01/DMux4Way
        run: ./tools/HardwareSimulator.sh ./01/DMux4Way.tst
      - name: Test Chapter 01/DMux8Way
        run: ./tools/HardwareSimulator.sh ./01/DMux8Way.tst

      - name: Test Chapter 02/HalfAdder
        run: ./tools/HardwareSimulator.sh ./02/HalfAdder.tst
      - name: Test Chapter 02/FullAdder
        run: ./tools/HardwareSimulator.sh ./02/FullAdder.tst
      - name: Test Chapter 02/Add16
        run: ./tools/HardwareSimulator.sh ./02/Add16.tst
      - name: Test Chapter 02/Inc16
        run: ./tools/HardwareSimulator.sh ./02/Inc16.tst
      - name: Test Chapter 02/ALU
        run: ./tools/HardwareSimulator.sh ./02/ALU.tst
